### ISSUE TITLE
server是怎样识别是否接收到client的连接

### ISSUE THREAD

**Issue by checkman-shy** [gnblao/workflow#4]
您好，我是一名初学者。想请教一下server是怎样识别是否接收到client的连接的？

**Comment by gnblao** [comment]
> 您好，我是一名初学者。想请教一下server是怎样识别是否接收到client的连接的？

要先建立起一个基础的网络通信模型。也就是从常说的tcp的三次握手开始，和四次挥手。
服务端的：socket->listen->accept
客户端的：socket->connect
这个很重要～～

**Comment by checkman-shy** [comment]
> 

您写的这个方法里面，ws_demo是没有实现连接建立之后的识别吗？似乎客户端给server发了消息，server才可以触发回复。而连接成功并不能有所表示

**Comment by gnblao** [comment]
> > 
> 
> 您写的这个方法里面，ws_demo是没有实现连接建立之后的识别吗？似乎客户端给server发了消息，server才可以触发回复。而连接成功并不能有所表示

是有的，只是wf架构设计之初应该就弱化了连接概念，认为只有连接成功发来请求才是一个正常的连接。
如果业务有对“新连接来了”这个动作需要感知的话，可以自己继承WFServer的new_connection的接口来感知一个连接来了
