### ISSUE TITLE
timer这么实现是不对的

### ISSUE THREAD

**Issue by Barenboim** [gnblao/workflow#7]
https://github.com/gnblao/workflow/blob/ad325be15120d9e1ef0bf475b4132aff1b3a3d69/src/kernel/mpoller.h#L87C1-L87C1

poller_add_timer之后，就不能对session的内容进行修改了，因为此时timer可能已经到期而且被释放了。而index和timerid都指向了session里的内容。
workflow里的原实现，index需要先赋值。如果你加上了timerid，那应该在poller里放timer之前，就把timerid先赋值了。参考timer做法。

**Comment by gnblao** [comment]
> https://github.com/gnblao/workflow/blob/ad325be15120d9e1ef0bf475b4132aff1b3a3d69/src/kernel/mpoller.h#L87C1-L87C1
> 
> poller_add_timer之后，就不能对session的内容进行修改了，因为此时timer可能已经到期而且被释放了。而index和timerid都指向了session里的内容。
> workflow里的原实现，index需要先赋值。如果你加上了timerid，那应该在poller里放timer之前，就把timerid先赋值了。参考timer做法。

好几天没上来了，这个确实有问题，后面我更新一下ʘ‿ʘ

**Comment by gnblao** [comment]
> https://github.com/gnblao/workflow/blob/ad325be15120d9e1ef0bf475b4132aff1b3a3d69/src/kernel/mpoller.h#L87C1-L87C1
> 
> poller_add_timer之后，就不能对session的内容进行修改了，因为此时timer可能已经到期而且被释放了。而index和timerid都指向了session里的内容。
> workflow里的原实现，index需要先赋值。如果你加上了timerid，那应该在poller里放timer之前，就把timerid先赋值了。参考timer做法。

Hi，楼主，请教个问题。你设计timer时候为啥会考虑用name_timer的方式来管理和关停timer，而不是用id的方式。在我看来以id方式比较直观，在poller这一层跟文件描述符fd有着相似的地方

**Comment by Barenboim** [comment]
我们不是一直是用name来标识一个资源的吗？比如url，计算队列名，timer/counter/mailbox的名称。产生一个唯一名称比产生一个唯一id要容易。

在核心代码里，我们是通过严格的时序来保证资源的有效性的，而不是产生允许失效的token让用户使用token来操作。

**Comment by gnblao** [comment]
> 我们不是一直是用name来标识一个资源的吗？比如url，计算队列名，timer/counter/mailbox的名称。产生一个唯一名称比产生一个唯一id要容易。
> 
> 在核心代码里，我们是通过严格的时序来保证资源的有效性的，而不是产生允许失效的token让用户使用token来操作。

嗯嗯，我大概理解了。之前在加双工通信时候想要timer的关停功能，加了一套基于bitmap的timerid生成功能，现在把两种timer实现都兼容了☺️
